### ISSUE TITLE
Esc prioritizes PASSTHROUGH mode over the command line

### ISSUE THREAD

**Issue by Enzime** [airodactyl/airodactyl#1]
Reproduction steps:
1. Add to ignorekeys any keybinding that opens the command line for a site
2. Open the command line whilst in PASSTHROUGH mode
3. Pressing Esc will exit PASSTHROUGH mode (which doesn't show as vimperator hides the status bar, showing the command mode overlayed on it)
4. Pressing Esc again will now exit the Command Line

Expected Behaviour:
3. Pressing Esc will exit Command Line

The question I have about this is: should the command line be treated as an input box and have INSERT mode bindings (and proper modes) or should it override everything and pretend as if it had no bindings except the default Firefox ones (permanent PASSTHROUGH).

**Comment by nathyong** [comment]
Command mode in vim is a separate mode from insert mode, and most people are probably not used to vim's insert mode while editing commands (unless they are familiar with `q:`). As such, I don't think the command line should be treated as an input box with insert mode bindings, and as long as it has C-w, which is probably the most people are expecting from such an input box.

**Comment by nathyong** [comment]
This appears to be an issue with the PASSTHROUGH mode specifically. Since Escape doesn't escape the old IGNORE ALL KEYS mode, this wasn't a problem until we implemented pentadactyl-like PASSTHROUGH. Personally I prefer the old behaviour since it's harder to actually escape from; is there a compromise?

**Comment by Enzime** [comment]
Well, my plan was to actually change it so that the way to exit from PASSTHROUGH would be entering PROCESS next (C-v) then hitting Esc, otherwise all Esc keys would be passed in PASSTHROUGH. This would mean that leaving PASSTHROUGH = C-v Esc, and leaving PROCESS (next) = Esc C-z (as you'd go back to the ACTUAL mode and need to re-enter PASSTHROUGH)

**Comment by Enzime** [comment]
Esc now works in 75aba6bb0907b749cbf0eef3f7382859714ed604, with the new changes to how PASSTHROUGH mode works and the code for handling it.
